"""
This modules takes as input the file generated by Stanford NER, and looks for the recognized entities.
For every entity, it looks on wikipedia for the article without doing any kind of preprocessing, query generation, or
any feature extraction.
If it finds a candidate article (any article), it assigns it to the entity.
If it doesn't, it classifies the entity as NIL.
"""

import wptools


class Mention:

    def __init__(self, string, cls):
        self.string = string
        self.cls = cls

    def __str__(self):
        return "{} - '{}'".format(self.cls, self.string)

    def __repr__(self):
        return "{} - '{}'".format(self.cls, self.string)


def process_file(file_name="output-ner"):
    result = []
    with open(file_name, "r") as f:
        for line in f:
            line = line.split('\t')
            if len(line) < 3 or not line[0]: continue
            result.append(Mention(line[0], line[1]))

    return result




