"""
This modules takes as input the file generated by Stanford NER, and looks for the recognized entities.
For every entity, it looks on wikipedia for the article without doing any kind of preprocessing, query generation, or
any feature extraction.
If it finds a candidate article (any article), it assigns it to the entity.
If it doesn't, it classifies the entity as NIL.
"""

import wptools


IGNORED_ENTITY_TYPES = {"ORDINAL", "NUMBER"}



def get_mentions_from_file(file_name):
    result = []
    i = 0
    previous_type = None
    with open(file_name, "r") as f:
        for line in f:
            if not line.strip():
                previous_type = None
                continue

            line = line.split('\t')
            entity_type = line[4]
            if entity_type != 'O' and entity_type not in IGNORED_ENTITY_TYPES:

                if entity_type == previous_type:
                    result[-1].add_word_to_mention(line[1])
                else:
                    result.append(Mention(line[1], line[4], i))

            i += 1
            previous_type = entity_type

    return result


def link_mentions(mentions):
    result = []
    for mention in mentions:
        try:
            page = wptools.page(mention.string).get_query()
        except LookupError:
            page = None

        result.append(LinkedMention(mention, page))

    return result
